version: '3.3'

services:
    app1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "Portofolio"
        ports:
            - "3000:3000"

    app:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: always
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./letsencrypt:/etc/letsencrypt
