version: '3.3'

services:
    app1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: portofolio
        # ports:
        #     - "3000:3000"
        networks:
            - my_network
    # app:
    #     image: 'jc21/nginx-proxy-manager:latest'
    #     restart: always
    #     ports:
    #         - '80:80'
    #         - '81:81'
    #         - '443:443'
    #     volumes:
    #         - ./data:/data
    #         - ./letsencrypt:/etc/letsencrypt
    #     networks:
    #         - app-network
    #     environment:
    #         DISABLE_IPV6: 'true'

networks:
    my_network:
        name: my_network
        driver: bridge

volumes:
    data:
    letsencrypt:
